apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: api
    workspace: images/api
  - imageName: frontend
    workspace: images/frontend
  - imageName: database
    workspace: images/database
  - imageName: apiwait
    workspace: images/api-wait
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_NAME}}:{{.DIGEST_ALGO}}-{{.DIGEST_HEX}}"
  local:
    skipPush: false
deploy:
  helm:
    releases:
      - name: "health-dev-{{.RELEASE_ID}}"
        chartPath: .
        values:
          overrideDatabaseImage: database
          overrideApiImage: api
          overrideApiwaitImage: apiwait
          overrideFrontendImage: frontend
        setValues:
          ingress.enabled: true
          ingress.host: ci-dev.us-south.containers.appdomain.cloud
