apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: source-to-image-health-frontend
spec:
  taskRef:
    name: source-to-image
  trigger:
    type: manual
  inputs:
    resources:
      - name: workspace
        resourceRef:
          name: health-helm-git
    params:
      - name: pathToContext
        value: images/frontend
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: health-frontend-image
