apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: helm-deploy-health
spec:
  taskRef:
    name: helm-deploy
  trigger:
    type: manual
  inputs:
    resources:
      - name: chart
        resourceRef:
          name: health-helm-git
      - name: api-image
        resourceRef:
          name: health-api-image
      - name: frontend-image
        resourceRef:
          name: health-frontend-image
      - name: database-image
        resourceRef:
          name: health-database-image
      - name: target-cluster
        resourceRef:
          name: mycluster
    params:
      - name: pathToHelmCharts
        value: .
      - name: clusterIngressHost
        value: mycluster.myzone.containers.appdomain.cloud
