kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.targetNamespace }}
  labels:
    name: helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.targetNamespace }}-helm
  namespace: {{ .Values.targetNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.targetNamespace }}-tiller-user
  namespace: {{ .Values.targetNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.targetNamespace }}-tiller-user-binding
  namespace: {{ .Values.targetNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.targetNamespace }}-tiller-user
subjects:
- kind: ServiceAccount
  name: {{ .Values.targetNamespace }}-helm
  namespace: {{ .Values.targetNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.targetNamespace }}-admin
  namespace: {{ .Values.targetNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.targetNamespace }}-admin-user-binding
  namespace: {{ .Values.targetNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.targetNamespace }}-admin
  namespace: {{ .Values.targetNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.targetNamespace }}-admin-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ .Values.targetNamespace }}-admin
