apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: helm-init
spec:
  serviceAccount: {{ .Values.targetNamespace }}-admin
  inputs:
    resources:
      - name: target-cluster
        type: cluster
  steps:
    - name: helm-init
      image: alpine/helm
      args:
        - init
        - --service-account={{ .Values.targetNamespace }}-admin
        - --wait
      env:
        - name: "KUBECONFIG"
          value: "/workspace/{{ .Values.targetCluster.name }}/kubeconfig"
        - name: "TILLER_NAMESPACE"
          value: "{{ .Values.targetNamespace }}"
