kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "health.fullname" . }}-services-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "health.fullname" . }}-read-services
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ template "health.fullname" . }}-services-reader
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.knative.enabled }}
apiVersion: serving.knative.dev/v1alpha1
kind: Service
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "health.fullname" . }}-api
  labels:
    app: {{ template "health.name" . }}-api
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.knative.enabled }}
  runLatest:
    configuration:
      revisionTemplate:  # template for building Revision
        spec:
          container:
{{- else }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "health.name" . }}-api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "health.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "health.fullname" . }}-api
{{- end }}
{{- if .Values.knative.enabled -}}
{{ include "health.api-container" . | nindent 12 }}
{{- else }}
{{ include "health.api-container" . | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "health.fullname" . }}-api
  labels:
    app: {{ template "health.name" . }}-api
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: health
    protocol: TCP
  selector:
    app: {{ template "health.name" . }}-api
    release: {{ .Release.Name }}
{{- end }}
{{- if .Values.databaseOverride }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ template "health.name" . }}-database-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.databaseOverride.host }}
  addresses:
  - {{ .Values.databaseOverride.ip }}
  ports:
  - name: tcp
    number: {{ .Values.databaseOverride.port }}
    protocol: tcp
  location: MESH_EXTERNAL
{{- end }}
