apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "health.fullname" . }}-frontend
  labels:
    app: {{ template "health.name" . }}-frontend
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "health.name" . }}-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "health.name" . }}-frontend
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ template "health.fullname" . }}-api-wait
        image: {{ template "health.api_wait.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/root/setvalue.sh"]
        env:
          - name: API_SECRET_NAME
            value: {{ template "health.fullname" . }}-apihost
          - name: API_CONTAINER_NAME
            value: {{ template "health.fullname" . }}-api
      containers:
        - name: {{ template "health.fullname" . }}-api
          image: {{ template "health.frontend.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "health.fullname" . }}-apihost
                  key: host
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "health.fullname" . }}-frontend
  labels:
    app: {{ template "health.name" . }}-frontend
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: health
    protocol: TCP
  selector:
    app: {{ template "health.name" . }}-frontend
    release: {{ .Release.Name }}
