{{- if .Values.knative.enabled }}
apiVersion: serving.knative.dev/v1alpha1
kind: Service
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "health.fullname" . }}-frontend
  labels:
    app: {{ template "health.name" . }}-frontend
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.knative.enabled }}
  runLatest:
    configuration:
      revisionTemplate:  # template for building Revision
        spec:
          container:
{{- else }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "health.name" . }}-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "health.name" . }}-frontend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "health.fullname" . }}-api
{{- end }}
{{- if .Values.knative.enabled -}}
{{ include "health.frontend-container" . | nindent 12 }}
{{- else }}
{{ include "health.frontend-container" . | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "health.fullname" . }}-frontend
  labels:
    app: {{ template "health.name" . }}-frontend
    chart: {{ template "health.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: health
    protocol: TCP
  selector:
    app: {{ template "health.name" . }}-frontend
release: {{ .Release.Name }}
{{- end }}
