{{- if .Values.ingress.enabled }}
{{- if not .Values.knative.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "health.fullname" . }}
  annotations:
    ingress.bluemix.net/rewrite-path: "serviceName={{ template "health.fullname" . }}-api rewrite=/;serviceName={{ template "health.fullname" . }}-frontend rewrite=/"
  labels:
    app: {{ template "health.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
   - host: "{{ .Values.ingress.host }}"
     http:
       paths:
         - path: /{{ .Release.Name }}-api
           backend:
             serviceName: {{ template "health.fullname" . }}-api
             servicePort: 80
         - path: /{{ .Release.Name }}-health
           backend:
             serviceName: {{ template "health.fullname" . }}-frontend
             servicePort: 80
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: istio-system
  name: {{ template "health.name" . }}-knative-ingress
spec:
  rules:
    - host: {{ template "health.name" . }}-frontend.{{ .Release.Namespace }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: istio-ingressgateway
              servicePort: 80
    - host: {{ template "health.name" . }}-api.{{ .Release.Namespace }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: istio-ingressgateway
              servicePort: 80
{{- end }}
{{- end }}
