kind: Namespace
apiVersion: v1
metadata:
  name: health
  labels:
    name: helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-helm
  namespace: health
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: health-tiller-user
  namespace: health
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-tiller-user-binding
  namespace: health
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: health-tiller-user
subjects:
- kind: ServiceAccount
  name: health-helm
  namespace: health
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-admin
  namespace: health
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-admin-user-binding
  namespace: health
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: health-admin
  namespace: health
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-admin-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: health-admin
